// examples/vite-vue/src/App.vue
<script setup lang="ts">
import { useQueryClient } from "@tanstack/vue-query";
import {
  getCityQueryKey,
  useGetCityQuery,
  useUpdateCityMutation,
} from "./generated/weather/src";

const queryClient = useQueryClient();
const { data, status } = useGetCityQuery({ cityId: "zrh" });
const { isPending: isSaving, mutate } = useUpdateCityMutation({
  onSuccess: (updatedCity, input) => {
    queryClient.setQueryData(
      getCityQueryKey({ cityId: input.cityId }),
      updatedCity,
    );
  },
});
</script>

<template>
  <main>
    <h1>smithy-vite + Vue</h1>
    <pre>{{ JSON.stringify(data ?? { status }, null, 2) }}</pre>
    <button
      :disabled="isSaving"
      @click="mutate({ cityId: 'zrh', temperatureCelsius: 22.5 })"
    >
      {{ isSaving ? "Saving…" : "Set temperature to 22.5 °C" }}
    </button>
  </main>
</template>

// examples/vite-preact/src/App.tsx
import { useQueryClient } from "@tanstack/preact-query";
import {
  getCityQueryKey,
  useGetCityQuery,
  useUpdateCityMutation,
} from "./generated/weather/src/index";

export function App() {
  const queryClient = useQueryClient();
  const city = useGetCityQuery({ cityId: "zrh" });
  const updateCity = useUpdateCityMutation({
    onSuccess: (updatedCity, input) => {
      queryClient.setQueryData(
        getCityQueryKey({ cityId: input.cityId }),
        updatedCity,
      );
    },
  });

  return (
    <main>
      <h1>smithy-vite + Preact</h1>
      <pre>{JSON.stringify(city.data ?? { status: city.status }, null, 2)}</pre>
      <button
        disabled={updateCity.isPending}
        onClick={() =>
          updateCity.mutate({ cityId: "zrh", temperatureCelsius: 22.5 })
        }
      >
        {updateCity.isPending ? "Saving…" : "Set temperature to 22.5 °C"}
      </button>
    </main>
  );
}
