// examples/vite-preact/src/main.tsx
import { QueryClient, QueryClientProvider } from "@tanstack/preact-query";
import { render } from "preact";
import { App } from "./App";
import {
  WeatherClient,
  WeatherClientProvider,
} from "./generated/weather/src/index";

const queryClient = new QueryClient();
const weatherClient = new WeatherClient({ endpoint: window.location.origin });

render(
  <QueryClientProvider client={queryClient}>
    <WeatherClientProvider client={weatherClient}>
      <App />
    </WeatherClientProvider>
  </QueryClientProvider>,
  document.getElementById("app")!,
);

// examples/vite-angular/src/main.ts
import { provideZonelessChangeDetection } from "@angular/core";
import { bootstrapApplication } from "@angular/platform-browser";
import {
  provideTanStackQuery,
  QueryClient,
} from "@tanstack/angular-query-experimental";
import { AppComponent } from "./app.component";
import { provideWeatherClient, WeatherClient } from "./generated/weather/src";

const weatherClient = new WeatherClient({ endpoint: window.location.origin });

bootstrapApplication(AppComponent, {
  providers: [
    provideZonelessChangeDetection(),
    provideTanStackQuery(new QueryClient()),
    provideWeatherClient(weatherClient),
  ],
}).catch((error: unknown) => console.error(error));
