// examples/vite-solid/src/main.tsx
import { QueryClient, QueryClientProvider } from "@tanstack/solid-query";
import { render } from "solid-js/web";
import { App } from "./App";
import {
  WeatherClient,
  WeatherClientProvider,
} from "./generated/weather/src/index";

const queryClient = new QueryClient();
const weatherClient = new WeatherClient({ endpoint: window.location.origin });

render(
  () => (
    <QueryClientProvider client={queryClient}>
      <WeatherClientProvider client={weatherClient}>
        <App />
      </WeatherClientProvider>
    </QueryClientProvider>
  ),
  document.getElementById("app")!,
);

// examples/vite-react/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { App } from "./App";

const queryClient = new QueryClient();

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <App />
    </QueryClientProvider>
  </StrictMode>,
);
